"Vim settings, rather than Vi settings
set nocompatible
" allow backspacing over everything in insert mode
set backspace=indent,eol,start
" ignore white spaces while using vimdiff
set diffopt+=iwhite
" ignoring case in a pattern
set ignorecase
set smartcase
" :0  no indent for case and default
" g0  no indent for public, protected and private
" lN  If N != 0 Vim will align with a case label instead of the statement
"     after it in the same line.
" tN  Indent a function return type declaration N characters from the margin
" details :help cinoptions-values
set cino+=:0,g0,l1,t0
" do not erase window
set t_ti= t_te=
"Show line number
set nu
"Auto align
set ai
"Tab width
set softtabstop=4
set sw=4
set expandtab
set tabstop=4

"Color scheme
colorscheme murphy
"Syntax highlight
syntax on
"Language for chinese
set fileencodings=ucs-dom,utf-8,gbk,latin1

"TagList "C+]"--Go to Function Define 
"        "C+T"--Go to the origin position
let Tlist_Ctags_Cmd="$HOME/.vim/ctags/bin/ctags"
let Tlist_Show_One_File=1
let Tlist_Exit_OnlyWindow=1

"WinManager
let g:winManagerWindowLayout='BufExplorer|FileExplorer|TagList'
let g:winManagerOnRightSide=1
let g:winManagerWidth=35
let g:AutoOpenWinManager=1
nmap <F2> :WMToggle<CR>
nmap <F5> :BufExplorer<CR>
nmap <F4> :qa!<CR>
nmap <F10> :wqa!<CR>
set tags=/da2/wangjingjing/wjj/tags
